# Generated by Django 4.1.8 on 2023-10-04 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image_file',
            new_name='image_file1',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_file2',
            field=models.ImageField(blank=True, null=True, upload_to='resimler/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
